name: Create release and archive

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create archive
        run: zip -r ${{ github.event.release.tag_name }}.zip .

      - name: Create release
        env:
          tag: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$tag" "${{github.event.release.tag_name}}.zip#ugr-latex-template-$tag.zip" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
